name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: burrunan/gradle-cache-action@v1
        name: Gradle Publish
        with:
          job-id: jdk11
          arguments: clean browserProductionWebpack dokkaHtml gitPublishPush
        env:
          GRGIT_USER: NyCodeGHG
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
